title: > TALIAS project : Natural Language Processing for indexing scientific
         articles

email: florian.boudin@univ-nantes.fr

description: > Home page of the TALIAS project : Natural Language Processing for
               indexing scientific articles.

theme: jekyll-theme-cayman